version: '3.9'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file:
      - ./apps/backend/.env
    environment:
      - DATABASE_URL=sqlite:///data/astra.db
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data
    depends_on:
      - redis

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  backend_data:
  redis_data: